### PR TITLE
HTTPResponse object has no attribute 'readall'

### PR DESCRIPTION
**Pull request by vmorris**
get_links() and download_link throwing:

AttributeError: 'HTTPResponse' object has no attribute 'readall'

Changed 'readall' to 'read'

### CODE REVIEW

**Comment by volker48** [comment]
What version of Python are you using? This was implemented and tested with version 3.4.2.

**Comment by volker48** [comment]
Just tested this it is indeed broken in python 3.5, but works fine in Python 3.4.2.

**Comment by volker48** [comment]
Thanks for the patch. `read()` works in both Python 3.4.2 and Python 3.5.

**Comment by vmorris** [comment]
Great, glad to help :+1:
